name: Build & Push Service Images

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        service: [api-gateway, inventory, order, payment, notification]

    env:
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase vars
        id: vars
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_LC=$(echo "${GITHUB_REPOSITORY#*/}" | tr '[:upper:]' '[:lower:]')
          echo "owner_lc=$OWNER_LC" >> $GITHUB_OUTPUT
          echo "repo_lc=$REPO_LC" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build only (for PRs)
      - name: Build (PR) – no push
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: ./services/${{ matrix.service }}
          push: false
          tags: ${{ env.REGISTRY }}/${{ steps.vars.outputs.owner_lc }}/${{ steps.vars.outputs.repo_lc }}-${{ matrix.service }}:pr-${{ github.event.pull_request.number }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build & push (on main)
      - name: Build & Push (main)
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v6
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.owner_lc }}/${{ steps.vars.outputs.repo_lc }}-${{ matrix.service }}:sha-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.owner_lc }}/${{ steps.vars.outputs.repo_lc }}-${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
